config/routes.rb
Rails.application.routes.draw do
  root 'pages#hem'
  get 'press' => "pages#press"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hem
  end
  
  def press
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Hem", root_path %></li>
      <li><%= link_to "Press", press_path %></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
    	<%= yield %>
	</div>

</body>
</html>

app/views/pages/hem.html.erb
<h1>INNANFÖR / WITHIN</h1>

<div align="center" class="embed-responsive embed-responsive-16by9">
        <iframe src="https://player.vimeo.com/video/158330269" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/158330269">within trailer</a> from <a href="https://vimeo.com/user4322308">Angela Bravo</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
</div>

<p>Om hur man upprätthåller den komplexa relationen till en intagen förälder som avtjänar livstidsstraff på obestämd tid. Filmen handlar om världen som finns innanför och inte syns, men ändå färgar av sig. Om kriminalvården, avstånd och kroppar som rastas. Om världens bästa pappa och kollektiv bestraffning. Om vad ovisshet, genomskinliga murar och dörrar utan handtag faktiskt gör med en. Filmaren Angela Bravo och hennes syskon växer upp och besöker honom på olika anstalter i Sverige, de spenderar sommarlov, födelsedagar och jular tillsammans. Fängelset blir som ett andra hem, ett ingenmansland. Filmen är en personlig komma ut film där regissören möter innanför, utanför.

<p>Missa inte regissören Angela Bravos besök till <%= link_to 'visningen den 11:e mars på Bio Rio!', "http://tempofestival.se/program/innanfor/" %></p>

app/views/pages/press.html.erb
<h1>Press</h1>

<p> This is where we put pressreleases</p>